"""drop_discovery_stats_from_keyword

Revision ID: 005c8266bfd3
Revises: a984ac3bc00b
Create Date: 2026-05-31 02:41:33.642434
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '005c8266bfd3'
down_revision: Union[str, None] = 'a984ac3bc00b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keyword', 'last_discovery_url_count')
    op.drop_column('keyword', 'last_discovery_duration_ms')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keyword', sa.Column('last_discovery_duration_ms', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('keyword', sa.Column('last_discovery_url_count', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
