"""add_collection_log

Revision ID: a984ac3bc00b
Revises: fa7e8223276a
Create Date: 2026-05-31 02:25:23.583161
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a984ac3bc00b'
down_revision: Union[str, None] = 'fa7e8223276a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_type', sa.String(length=20), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('keyword_id', sa.BigInteger(), nullable=True),
    sa.Column('portal_type', sa.String(length=20), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('urls_found', sa.Integer(), nullable=True),
    sa.Column('urls_inserted', sa.Integer(), nullable=True),
    sa.Column('urls_skipped', sa.Integer(), nullable=True),
    sa.Column('urls_attempted', sa.Integer(), nullable=True),
    sa.Column('urls_success', sa.Integer(), nullable=True),
    sa.Column('urls_failed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_collection_log_date_type', 'collection_log', ['run_date', 'run_type'], unique=False)
    op.create_index('ix_collection_log_keyword_date', 'collection_log', ['keyword_id', 'run_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_collection_log_keyword_date', table_name='collection_log')
    op.drop_index('ix_collection_log_date_type', table_name='collection_log')
    op.drop_table('collection_log')
    # ### end Alembic commands ###
