"""add_discovery_stats_to_keyword

Revision ID: fa7e8223276a
Revises: 0ce5fb2154d2
Create Date: 2026-05-31 02:15:20.041850
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'fa7e8223276a'
down_revision: Union[str, None] = '0ce5fb2154d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keyword', sa.Column('last_discovery_duration_ms', sa.Integer(), nullable=True))
    op.add_column('keyword', sa.Column('last_discovery_url_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keyword', 'last_discovery_url_count')
    op.drop_column('keyword', 'last_discovery_duration_ms')
    # ### end Alembic commands ###
